version: '3'

services:
  # Proxies requests to internal services
  proxy:
    image: nginx
    container_name: proxy
    depends_on:
        - frontend-web
        - api-web
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80


  frontend-web:
    image: frontend-web
    container_name: frontend-web
    build:
      context: ./root
    depends_on:
        - api-web
    ports:
      - 8082:80
    restart: on-failure

  api-web:
    image: api-web
    container_name: api-web
    build:
      context: ./newsapi
    ports:
      - 8083:80
    restart: on-failure

 
